{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: /circle-ci/backend
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.service.port }}
  {{- end }}
