replicaCount: 1

image:
  repository: 038062473746.dkr.ecr.us-east-1.amazonaws.com/circleci-petclinic-frontend
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  hosts: harness-backend.funatlearn.com
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip